config/routes.rb
FilderViewer::Application.routes.draw do
  root :to => 'resources#index'
  
  resources :users
  resources :login do
    collection do
      post "login"
      get "logout"
    end
  end
  resources :canvas do
    collection do
      get "draw"
    end
  end
  resources :resources

end

app/models/user.rb
# -*- encoding : utf-8 -*-
class User < ActiveRecord::Base
  validates_presence_of :name
  validates :password,
    :length => {:minimum => 8}
  validates_confirmation_of :password
  validates_uniqueness_of :name, :allow_blank => true  
  attr_accessor :password, :password_confirmation
  
  #ハッシュパスワードとソルトを設定する
  def password=(val)
    @password = val
    return unless val and val.size > 0
    self.salt = rand(7777777)
    self.hashed_password = User.hashed_password(val,salt)
  end
  
  #パスワードを暗号化する
  def self.hashed_password(password,salt)
    Digest::SHA1.hexdigest(sprintf("%s08d", password, salt))
  end
  
  #認証を行う
  def self.authenticate(name,password)
    user = User.find_by_name(name)
    if user and user.hashed_password == User.hashed_password(password, user.salt)
      user
    else
      nil
    end
  end
  
end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :block_unsigned_user unless Rails.env == 'test'
  
  def block_unsigned_user
    redirect_to login_index_path unless session[:user] 
  end
end

app/controllers/canvas_controller.rb
class CanvasController < ApplicationController
  def index
    if params[:path]
      begin
        file = File.open(params[:path],"r")
        @json = file.read if file
        file.close
      rescue
        flash[:message] = "File not found!"
      end
    end
  end
  def draw
    @json = File.open("tmp/test.json","r").read
    respond_to do |format|
      format.html # new.html.erb
      format.js
    end
  end
end

app/controllers/login_controller.rb
# -*- encoding : utf-8 -*-
class LoginController < ApplicationController
  skip_before_filter :block_unsigned_user

  #ログイン画面
  def index
    @without_menu = true
  end
  
  #ログイン
  def login
    user = User.authenticate(params[:name], params[:password])
    if user
      session[:user] = user.name
      redirect_to "/"
    else
      flash.now[:message] = "アドレスまたはパスワードが間違っています。"
      @without_menu = true
      render :action => "index"
    end
  end
  
  #ログアウト
  def logout
    reset_session
    redirect_to login_index_path
  end
end

app/controllers/resources_controller.rb
# -*- encoding : utf-8 -*-
class ResourcesController < ApplicationController
 include ApplicationHelper
 
  def index
    @files = []
    Dir.glob(user_directory + '/*.{json}') do |file|
      @files << file
    end
  end
  
  def new
    
  end
  
  def create
    if params[:path]
      file = params[:path]
      filename = file.original_filename
      new_path = user_directory + "/" +filename
      
      if File.exist?(new_path)
        flash[:message] = "指定されたファイルは既に存在しています。"
        render "new"
        return
      end
      begin
        io = File.open(new_path,"w")
        io.write(file.read)
        io.close
        flash[:notice] = "ファイルのアップロードを行いました。"
        redirect_to resources_path
      rescue
        flash[:message] = "ディレクトリが見つかりません。"
        render "new"
      end
    else
      flash[:message] = "ファイルを選択してください。"
      render "new"
    end
  end
  
end

app/controllers/users_controller.rb
# -*- encoding : utf-8 -*-
class UsersController < ApplicationController
  skip_before_filter :block_unsigned_user
  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    @without_menu = true
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    @without_menu = true
    respond_to do |format|
      if @user.save
        #アカウントのディレクトリ作成
        if File::ftype(FILE_DIRECTORY + "/" + @user.name) != "directory"
          Dir::mkdir(FILE_DIRECTORY + "/" + @user.name)
        end
        format.html { redirect_to login_index_path, notice: 'ユーザーを作成しました。' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
module ApplicationHelper  
  #フラッシュでエラーメッセージを表示する  
  def flash_error_message
    return unless flash[:message]
    content_tag :div, {:id => "error_explanation"} do 
      content_tag :h2,flash[:message]
    end
  end
  
  #モデル属性名を取得する
  def attr_name(object, name)
    if object.kind_of?(String) or object.kind_of?(Symbol)
      classname = object.to_s
    else
      classname = object.class.name.downcase
    end
    I18n.t( 'activerecord.attributes.' + classname + '.' + name.to_s)
  end
  
  def required
    content_tag(:span,'*',{:class => "required"})
  end
 
 def li_with_active(path, &block)
   content_tag(:li, {:class => path == request.path ? "active" : ""},&block)
 end
 
 def user_directory
   return FILE_DIRECTORY + '/' + session[:user]
 end
end

app/helpers/canvas_helper.rb
module CanvasHelper
end

app/helpers/login_helper.rb
# -*- encoding : utf-8 -*-
module LoginHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
  def get_filename(path)
    splits = path.split(/\//)
    splits[splits.length-1]
  end
end

app/helpers/users_helper.rb
# -*- encoding : utf-8 -*-
module UsersHelper
end

app/views/canvas/draw.js.erb
var data = '<%=escape_javascript(@json)%>';
var obj = parse_json(data)
canvas = new Canvas(obj);
canvas.draw();

app/views/canvas/index.html.erb
<%=render :partial => "shared/simple_error_message"%>
<%@without_container = true%>
<div id= "canvas_container" class="box">
	<canvas id="main">
		<script>
			new Background(500,500).draw();
		</script>
		<%if @json%>
			<script>
				new Canvas(parse_json('<%=escape_javascript(@json)%>')).draw();
			</script>
		<%end%>
	</canvas>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=@document_title + ": " if @document_title%>FilderViewer</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%unless @without_menu%>
	<%=render "shared/header"%>
<%end%>
<div class=<%="container" unless @without_container%> >
<%= yield %>
</div>

</body>
</html>

app/views/login/index.html.erb
<%@document_title = 'ログイン'%>

<%=form_tag :action => "login", :method => :post, :class=>"well" do%>
<div class="hero-unit box" style="width: 320px">
	<div class="title">
		<h1>FilderViewer</h1>		
	</div>
	<%=render :partial=>"shared/simple_notice_message"%>
	<%=render :partial=>"shared/simple_error_message"%>
	<div class="form box">
		<label><%=attr_name(:user, :name)%></label>
		<%=text_field_tag :name, "",{:size =>35}%>
		<label><%=attr_name(:user, :password)%></label>
		<%=password_field_tag :password, "",{:size =>35}%>
		<p class="submit">
			<%=submit_tag 'ログイン', :class =>'btn btn-large btn-primary'%>
		</p>
		<span class="pull-right">		
			<%=link_to 'ユーザー登録≫', new_user_path, {:class => 'btn'}%>
		</span>
	</div>
<%end%>
</div>

app/views/resources/index.html.erb
<%=render :partial=>"shared/simple_notice_message"%>

<div style="float: right">
<%=link_to new_resource_path, {:class => "btn btn-success"} do%>
	<i class ="icon-plus icon-white"></i>
	ファイル追加
<%end%>
</div>

<table class="table table-striped">
<%@files.each do |file|%>
	<tr>
		<td><%=link_to get_filename(file), canvas_path(:path =>file)%></td>
	</tr>
<%end%>
	
</table>

app/views/resources/new.html.erb
<div class="hero-unit box" style="width: 400px">
  <div class="title">
  	<h1>File Upload</h1>
  </div>
  <%=form_tag '/resources', :multipart => true do%>
	<%=render :partial => "shared/simple_error_message"%>
	<%=file_field_tag "path", :accept => "application/json"%>
	  <p class="submit pull-right">
	  	<%=link_to "キャンセル", resources_path, :class => "btn btn-large"%>
	  	<%=submit_tag "アップロード", :class => "btn btn-primary btn-large"%>
	  </p>				
	<%end%>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
	  <h2><%= object.errors.count%> 個の入力エラーがあります:</h2>
	
	  <ul>
	  <% object.errors.full_messages.each do |msg| %>
	    <li><%= msg %></li>
	  <% end %>
	  </ul>
	</div>
<%end%>

app/views/shared/_header.html.erb
<div class="navbar navbar-fixed-top">
<div class="navbar navbar-inner">
    <div class="container">
      <ul class="nav">
		<label class="brand">Filder Viewer</label>

		<li class="divider-vertical"></li>
		  <%=li_with_active(resources_path) do%>
			  <%=link_to resources_path do%>
					<i class ="icon-list icon-white"></i>
					List
				<%end%>
		  <%end%>
		</ul>
		<ul class="nav pull-right">
			<li class="dropdown">
				  <a class="dropdown-toggle btn-large" data-toggle="dropdown" href="#">
				    <i class="icon-user icon-white"></i>
				    <%=session[:user]%>
				    <b class="caret"></b>
				  </a>
				  <ul class="dropdown-menu">
				  	<li><%=link_to "ログアウト", logout_login_index_path%></li>
				  </ul>
			</li>
		</ul>
    </div>
</div>
</div>

app/views/shared/_simple_error_message.html.erb
<%if flash[:message]%>
	<div class="alert alert-error fade in">
		<a class="close" data-dismiss="alert" href="#">×</a>
		<trong><%=flash[:message]%></strong>	
	</div>
<%end%>

app/views/shared/_simple_notice_message.html.erb
<%if flash[:notice]%>
	<div class="alert alert-success fade in">
		<a class="close" data-dismiss="alert" href="#">×</a>
		<trong><%=flash[:notice]%></strong>	
	</div>
<%end%>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
		<label><%= attr_name(:user, :name) %></label>
		<%= f.text_field :name %>
		<label><%= attr_name(:user, :password) %></label>
		<%= f.password_field :password %>
		<label><%= attr_name(:user, :password_confirmation) %></label>
		<%= f.password_field :password_confirmation%>
		<p class="submit">
			<%= f.submit "登録", :class=> "btn btn-large"%>
			<%=link_to "キャンセル", login_index_path, {:class => 'btn btn-large'}%>
		</p>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%@document_title = "ユーザー登録"%>
	<div class="hero-unit box" style="width: 320px">
		<div class="title">
			<h1>FilderViewer</h1>
			<h2>ユーザー登録</h2>
		</div>
		<%=render :partial => "shared/error_messages", :locals=>{:object => @user}%>
		<%= render 'form' %>
	</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>